### ISSUE TITLE
About You - Input Fields not clipped on page

### ISSUE THREAD

**Issue by jprincipe** [rocketinsights/q-streak-ios#10]
![Simulator Screen Shot - iPhone 11 Pro - 2020-04-28 at 08 52 35](https://user-images.githubusercontent.com/864799/80489557-fda1e280-892d-11ea-9d93-fb24bb9db4f1.png)

**Comment by MarshallMcCoy** [comment]
Fixed by: https://github.com/rocketinsights/q-streak-ios/pull/14
